Use HTML "title" attribute on plugin's button
globocom/generator-megadraft-plugin pull request #2
Opened 2017-01-02 18:26 UTC by hermancaldara

Updates the generator to create the package with buttons with attr "title".

2017-01-02 21:32 UTC, marcelometal requested changes
Hi @hermancaldara, Could you please fix the syntax error?

Thanks for contributing to Megadraft!

2017-01-02 21:32 UTC, marcelometal commented on generators/app/templates/src/constants.js
> +  PLUGIN_NAME: "<%= inputs.pluginName %>"
Hi @hermancaldara, please add a comma here ;)

2017-01-03 12:09 UTC, hermancaldara commented
Done! Sorry for that, @marcelometal.

2017-01-03 13:05 UTC, merged

2017-01-03 13:05 UTC, marcelometal commented
Thanks for contributing to Megadraft!